# Generated by Django 4.0 on 2021-12-26 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('title', models.CharField(max_length=15)),
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=20)),
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='posts/')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ishita.category')),
            ],
        ),
    ]
