# Generated by Django 4.0 on 2021-12-26 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ishita', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cat',
            new_name='category',
        ),
    ]
