# Generated by Django 4.0 on 2021-12-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishita', '0003_post_add_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
