# Generated by Django 4.0 on 2021-12-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishita', '0007_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
