# Generated by Django 4.0 on 2021-12-29 08:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ishita', '0008_information_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='about',
            field=tinymce.models.HTMLField(),
        ),
    ]
