# Generated by Django 4.0 on 2021-12-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishita', '0010_information_greetings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillname', models.CharField(max_length=25)),
            ],
        ),
    ]
