# Generated by Django 4.0 on 2021-12-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishita', '0011_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name_plural': 'Infromation'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name_plural': 'Skills'},
        ),
        migrations.AddField(
            model_name='skills',
            name='image_link',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skills',
            name='skillname',
            field=models.CharField(max_length=35),
        ),
    ]
