# Generated by Django 4.0 on 2021-12-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishita', '0002_rename_cat_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
