# Generated by Django 4.0 on 2021-12-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishita', '0006_alter_category_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=55)),
                ('linkedin', models.CharField(max_length=100)),
                ('gmail', models.CharField(max_length=100)),
                ('behance', models.CharField(max_length=100)),
            ],
        ),
    ]
