# Generated by Django 4.0 on 2021-12-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishita', '0009_alter_information_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='greetings',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
